language: python
python:
  - "2.7"
install:
  - pip install -e .
before_script:
  - pip install -e ."[tests]"
script:
  - pytest
after_success:
  - pip install coveralls
  - coveralls
notifications:
    email:
        on_success: change
        on_failure: change
